import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navbar, NavbarBrand, NavbarContent, NavbarItem, Link } from "@nextui-org/react";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar>
          <NavbarContent className="hidden sm:flex gap-4" justify="start">
            <NavbarItem>
              <Link href="/design">Design</Link>
            </NavbarItem>
            <NavbarItem>
              <Link href="/contact">Contact</Link>
            </NavbarItem>
          </NavbarContent>
          <NavbarBrand className="text-2xl font-bold text-inherit justify-start flex">
            {/* <Logo></Logo> */}
            <Link className = "text-4xl" href="/">Charles Oliver</Link>
          </NavbarBrand>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
